# Web Scraping Using Instant Data Scraper

In [4]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv("bigboytoyz.csv")
df

,bgimg href,cntnt-grp,model,kms,fueltype
0,https://www.bigboytoyz.com/used-luxury-cars/me...,2019 MERCEDES BENZ V220D with Maybach Kit,- 2019,- 46250,- Diesel
1,https://www.bigboytoyz.com/used-luxury-cars/bm...,2022 BMW X4 XDRIVE30d M SPORT X SILVER SHADOW ...,- 2022,- 32500,- Diesel
2,https://www.bigboytoyz.com/used-luxury-cars/me...,2024 Mercedes Benz A200 Limousine,- 2025,- 3100,- Petrol
3,https://www.bigboytoyz.com/used-luxury-cars/bm...,2024 BMW 740I M SPORT,- 2024,- 20800,- Petrol
4,https://www.bigboytoyz.com/used-luxury-cars/vo...,2019 VOLVO XC90 D5 Inscription,- 2019,- 74200,- Diesel
5,https://www.bigboytoyz.com/used-luxury-cars/la...,2024 Land Rover Defender 110 P300 HSE,- 2025,- 9700,- Petrol
6,https://www.bigboytoyz.com/used-luxury-cars/me...,2019 MERCEDES BENZ V220D with Maybach Kit,- 2019,- 46250,- Diesel
7,https://www.bigboytoyz.com/used-luxury-cars/bm...,2022 BMW X4 XDRIVE30d M SPORT X SILVER SHADOW ...,- 2022,- 32500,- Diesel
8,https://www.bigboytoyz.com/used-luxury-cars/me...,2024 Mercedes Benz A200 Limousine,- 2025,- 3100,- Petrol
9,https://www.bigboytoyz.com/used-luxury-cars/bm...,2024 BMW 740I M SPORT,- 2024,- 20800,- Petrol
10,https://www.bigboytoyz.com/used-luxury-cars/vo...,2019 VOLVO XC90 D5 Inscription,- 2019,- 74200,- Diesel
11,https://www.bigboytoyz.com/used-luxury-cars/la...,2024 Land Rover Defender 110 P300 HSE,- 2025,- 9700,- Petrol
12,https://www.bigboytoyz.com/used-luxury-cars/me...,2019 MERCEDES BENZ V220D with Maybach Kit,- 2019,- 46250,- Diesel

# Data Transformation

In [6]:
df = df.drop(columns=['bgimg href'])
df

,cntnt-grp,model,kms,fueltype
0,2019 MERCEDES BENZ V220D with Maybach Kit,- 2019,- 46250,- Diesel
1,2022 BMW X4 XDRIVE30d M SPORT X SILVER SHADOW ...,- 2022,- 32500,- Diesel
2,2024 Mercedes Benz A200 Limousine,- 2025,- 3100,- Petrol
3,2024 BMW 740I M SPORT,- 2024,- 20800,- Petrol
4,2019 VOLVO XC90 D5 Inscription,- 2019,- 74200,- Diesel
5,2024 Land Rover Defender 110 P300 HSE,- 2025,- 9700,- Petrol
6,2019 MERCEDES BENZ V220D with Maybach Kit,- 2019,- 46250,- Diesel
7,2022 BMW X4 XDRIVE30d M SPORT X SILVER SHADOW ...,- 2022,- 32500,- Diesel
8,2024 Mercedes Benz A200 Limousine,- 2025,- 3100,- Petrol
9,2024 BMW 740I M SPORT,- 2024,- 20800,- Petrol
10,2019 VOLVO XC90 D5 Inscription,- 2019,- 74200,- Diesel
11,2024 Land Rover Defender 110 P300 HSE,- 2025,- 9700,- Petrol
12,2019 MERCEDES BENZ V220D with Maybach Kit,- 2019,- 46250,- Diesel

In [7]:
df['model'] = df['model'].astype(str).str.replace('-', '', regex=False)
df['kms'] = df['kms'].astype(str).str.replace('-', '', regex=False)
df['fueltype'] = df['fueltype'].str.replace('-','',regex=False)
df

                                            cntnt-grp  model     kms fueltype
0           2019 MERCEDES BENZ V220D with Maybach Kit   2019   46250   Diesel
1   2022 BMW X4 XDRIVE30d M SPORT X SILVER SHADOW ...   2022   32500   Diesel
2                   2024 Mercedes Benz A200 Limousine   2025    3100   Petrol
3                               2024 BMW 740I M SPORT   2024   20800   Petrol
4                      2019 VOLVO XC90 D5 Inscription   2019   74200   Diesel
5               2024 Land Rover Defender 110 P300 HSE   2025    9700   Petrol
6           2019 MERCEDES BENZ V220D with Maybach Kit   2019   46250   Diesel
7   2022 BMW X4 XDRIVE30d M SPORT X SILVER SHADOW ...   2022   32500   Diesel
8                   2024 Mercedes Benz A200 Limousine   2025    3100   Petrol
9                               2024 BMW 740I M SPORT   2024   20800   Petrol
10                     2019 VOLVO XC90 D5 Inscription   2019   74200   Diesel
11              2024 Land Rover Defender 110 P300 HSE   2025    9700   Petrol
12          2019 MERCEDES BENZ V220D with Maybach Kit   2019   46250   Diesel

In [66]:
df['brand'] = df['cntnt-grp'].str.split().str[1]

In [68]:
print(df.describe())
df.isnull().sum()

                                        cntnt-grp  model     kms fueltype  \
count                                          13     13      13       13
unique                                          6      4       6        2
top     2019 MERCEDES BENZ V220D with Maybach Kit   2019   46250   Diesel
freq                                            3      5       3        7

       brand
count     13
unique     5
top      BMW
freq       4

cntnt-grp    0
model        0
kms          0
fueltype     0
brand        0
dtype: int64

In [127]:
df

,cntnt-grp,model,kms,fueltype,brand
0,2019 MERCEDES BENZ V220D with Maybach Kit,2019,46250,Diesel,2
1,2022 BMW X4 XDRIVE30d M SPORT X SILVER SHADOW ...,2022,32500,Diesel,0
2,2024 Mercedes Benz A200 Limousine,2025,3100,Petrol,3
3,2024 BMW 740I M SPORT,2024,20800,Petrol,0
4,2019 VOLVO XC90 D5 Inscription,2019,74200,Diesel,4
5,2024 Land Rover Defender 110 P300 HSE,2025,9700,Petrol,1
6,2019 MERCEDES BENZ V220D with Maybach Kit,2019,46250,Diesel,2
7,2022 BMW X4 XDRIVE30d M SPORT X SILVER SHADOW ...,2022,32500,Diesel,0
8,2024 Mercedes Benz A200 Limousine,2025,3100,Petrol,3
9,2024 BMW 740I M SPORT,2024,20800,Petrol,0
10,2019 VOLVO XC90 D5 Inscription,2019,74200,Diesel,4
11,2024 Land Rover Defender 110 P300 HSE,2025,9700,Petrol,1
12,2019 MERCEDES BENZ V220D with Maybach Kit,2019,46250,Diesel,2

In [158]:
lb = LabelEncoder()
df['brand'] = lb.fit_transform(df['brand'])
df['fueltype'] = lb.fit_transform(df['fueltype'])
df

,cntnt-grp,model,kms,fueltype,brand
0,2019 MERCEDES BENZ V220D with Maybach Kit,2019,46250,0,2
1,2022 BMW X4 XDRIVE30d M SPORT X SILVER SHADOW ...,2022,32500,0,0
2,2024 Mercedes Benz A200 Limousine,2025,3100,1,3
3,2024 BMW 740I M SPORT,2024,20800,1,0
4,2019 VOLVO XC90 D5 Inscription,2019,74200,0,4
5,2024 Land Rover Defender 110 P300 HSE,2025,9700,1,1
6,2019 MERCEDES BENZ V220D with Maybach Kit,2019,46250,0,2
7,2022 BMW X4 XDRIVE30d M SPORT X SILVER SHADOW ...,2022,32500,0,0
8,2024 Mercedes Benz A200 Limousine,2025,3100,1,3
9,2024 BMW 740I M SPORT,2024,20800,1,0
10,2019 VOLVO XC90 D5 Inscription,2019,74200,0,4
11,2024 Land Rover Defender 110 P300 HSE,2025,9700,1,1
12,2019 MERCEDES BENZ V220D with Maybach Kit,2019,46250,0,2

# Data Dividation

In [161]:
x = df.drop(columns=['fueltype','cntnt-grp'])
y = df['fueltype']

In [163]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler

# Spliting Training and Testing

In [166]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

# Standarization

In [169]:
sc = StandardScaler()
x_train_sc = sc.fit_transform(x_train)
x_train_new = pd.DataFrame(x_train_sc,columns=x_train.columns)
np.round(x_train_new.describe(),2)

       model    kms  brand
count  10.00  10.00  10.00
mean   -0.00   0.00   0.00
std     1.05   1.05   1.05
min    -1.12  -1.25  -1.26
25%    -1.12  -0.87  -1.09
50%     0.04  -0.07   0.07
75%     1.10   0.48   0.73
max     1.20   1.60   1.39

# Normalization

In [172]:
mn = MinMaxScaler()

In [174]:
x_train_mn = mn.fit_transform(x_train)
x_train_new = pd.DataFrame(x_train_mn,columns=x.columns)
np.round(x_train_new.describe(),2)

       model    kms  brand
count  10.00  10.00  10.00
mean    0.48   0.44   0.48
std     0.45   0.37   0.40
min     0.00   0.00   0.00
25%     0.00   0.13   0.06
50%     0.50   0.41   0.50
75%     0.96   0.61   0.75
max     1.00   1.00   1.00